site_name: X3Plus Documentation
docs_dir: docs
site_url: https://cord-burmeister.github.io/x3plus_docs/
theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
  features:
    - navigation.top
    - navigation.expand
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js      