site_name: X3Plus Documentation
docs_dir: docs
site_url: https://cord-burmeister.github.io/x3plus_docs/
theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
  features:
    - navigation.top
    - navigation.expand
